# stack p4nr
version: '3.1'

services:
    nodered:
      container_name: node_red
      image: p4nr/node-red:latest
      restart: always
      environment:
        - TZ=Europe/Amsterdam
        - P4NR_LICENSE_TOKEN=$NPM_TOKEN
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - data:/data
      ports:
        - "1881:1880"
        - "1502:10502"
        - "14840:14840"
        - "14841:14841"

volumes:
  data:
    driver: local
