# stack p4nr
version: '3.1'

services:
    nodered:
      container_name: node_red
      image: docker.cloudsmith.io/iniationware-gmbh/flowforge/p4nr/node-red:latest
      restart: always
      environment:
        - TZ=Europe/Amsterdam
        - P4NR_LICENSE_TOKEN=$NPM_TOKEN
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - data:/data
        - config:/config
        - nodes:/nodes
      ports:
        - "1881:1881"
        - "1502:10502"
        - "14840:14840"
        - "14841:14841"
        - "14842:14842"
        - "14845:14845"

volumes:
  data:
    driver: local
  config:
    driver: local
  nodes:
    driver: local