# stack p4nr
version: '3.1'

services:
    nodered:
      container_name: node_red
      image: p4nr/node-red:latest
      restart: unless-stopped
      environment:
        - TZ=Europe/Amsterdam
        - P4NR_LICENSE_TOKEN=$NPM_TOKEN
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - data:/data
        - config:/config
        - nodes:/nodes
      ports:
        - "1885:1881"
        - "1503:10502"

volumes:
  data:
    driver: local
  config:
    driver: local
  nodes:
    driver: local